Crazy Eddie's GUI System: CEGUI::IrrlichtEventPusher Class Reference
CEGUI::IrrlichtEventPusher Class Reference
Public Member Functions
IrrlichtEventPusher (irr::gui::ICursorControl *ctrl)
bool OnEvent (const SEvent &event)
bool OnKeyDown (EKEY_CODE key, wchar_t wch, bool, bool)
bool OnKeyUp (EKEY_CODE key, wchar_t, bool, bool)
bool OnMouse (s32 x, s32 y, f32 w, EMOUSE_INPUT_EVENT e)
CEGUI::Key::Scan getKeyCode (irr::EKEY_CODE kc) const
Protected Member Functions
void initCodes ()
Protected Attributes
CEGUI::Key::Scan irr2ceCODE [irr::KEY_KEY_CODES_COUNT]
Member Function Documentation
CEGUI::Key::Scan CEGUI::IrrlichtEventPusher::getKeyCode (irr::EKEY_CODE kc) const inline
translate the irrlicht keycode to cegui keycode
Parameters
kc the irrlicht keycode
Returns
the cegui keycode
bool CEGUI::IrrlichtEventPusher::OnMouse (s32 x, s32 y, f32 w, EMOUSE_INPUT_EVENT e) inline
Left mouse button was pressed down.
Right mouse button was pressed down.
Middle mouse button was pressed down.
Left mouse button was left up.
Right mouse button was left up.
Middle mouse button was left up.
The mouse cursor changed its position.
The mouse wheel was moved. Use Wheel value in event data to find out in what direction and how fast.
References CEGUI::System::getSingleton(), CEGUI::GUIContext::injectMouseButtonDown(), CEGUI::GUIContext::injectMouseButtonUp(), CEGUI::GUIContext::injectMousePosition(), CEGUI::GUIContext::injectMouseWheelChange(), CEGUI::LeftButton, CEGUI::MiddleButton, and CEGUI::RightButton.