Crazy Eddie's GUI System: CEGUI::TypedProperty< T > Class Template Reference
CEGUI::TypedProperty< T > Class Template Reference abstract
base class for properties able to do native set/get
Public Types
typedef PropertyHelper< T > Helper
Public Member Functions
TypedProperty (const String &name, const String &help, const String &origin="Unknown", typename Helper::pass_type defaultValue=T(), bool writesXML=true)
virtual String get (const PropertyReceiver *receiver) const
Return the current value of the Property as a String.
virtual void set (PropertyReceiver *receiver, const String &value)
Sets the value of the property.
virtual void setNative (PropertyReceiver *receiver, typename Helper::pass_type value)
native set method, sets the property given a native type
virtual
Helper::safe_method_return_type getNative (const PropertyReceiver *receiver) const
native get method, returns the native type by copy
Public Member Functions inherited from CEGUI::Property
Property (const String &name, const String &help, const String &defaultValue="", bool writesXML=true, const String &dataType="Unknown", const String &origin="Unknown")
Creates a new Property object.
virtual ~Property (void)
Destructor for Property objects.
const String & getHelp (void) const
Return a String that describes the purpose and usage of this Property.
const String & getName (void) const
Return a the name of this Property.
const String & getDataType (void) const
Return string data type of this Property.
const String & getOrigin (void) const
Return string origin of this Property.
virtual bool isDefault (const PropertyReceiver *receiver) const
Returns whether the property is at it's default value.
virtual String getDefault (const PropertyReceiver *receiver) const
Returns the default value of the Property as a String.
virtual void writeXMLToStream (const PropertyReceiver *receiver, XMLSerializer &xml_stream) const
Writes out an XML representation of this class to the given stream.
virtual bool isReadable () const
Returns whether the property is readable.
virtual bool isWritable () const
Returns whether the property is writable.
virtual bool doesWriteXML () const
Returns whether the property writes to XML streams.
virtual void initialisePropertyReceiver (PropertyReceiver *) const
function to allow initialisation of a PropertyReceiver.
virtual Property * clone () const =0
Protected Member Functions
virtual void setNative_impl (PropertyReceiver *receiver, typename Helper::pass_type value)=0
virtual
Helper::safe_method_return_type getNative_impl (const PropertyReceiver *receiver) const =0
Additional Inherited Members
Static Public Attributes inherited from CEGUI::Property
static const String XMLElementName
static const String NameXMLAttributeName
static const String ValueXMLAttributeName
Protected Attributes inherited from CEGUI::Property
String d_name
String that stores the Property name.
String d_help
String that stores the Property help text.
String d_default
String that stores the Property default value string.
bool d_writeXML
Specifies whether writeXMLToStream should do anything for this property.
String d_dataType
Holds data type of this property.
String d_origin
Holds origin of this property.
Detailed Description
template<typename T>
class CEGUI::TypedProperty< T >
base class for properties able to do native set/get
Todo:
I split this from CEGUIProperty.h to avoid bloating it with PropertyHelper, I also split it from TplProperty since it can be used outside of that. Is that the "right thing" to do?
Member Function Documentation
template<typename T> virtual String CEGUI::TypedProperty< T >::get (const PropertyReceiver * receiver) const inline virtual
Return the current value of the Property as a String.
Parameters
receiver Pointer to the target object.
Returns
String object containing a textual representation of the current value of the Property
Implements CEGUI::Property.
template<typename T> virtual Helper::safe_method_return_type CEGUI::TypedProperty< T >::getNative (const PropertyReceiver * receiver) const inline virtual
native get method, returns the native type by copy
See Also
Property::get
Referenced by CEGUI::TypedProperty< String >::get(), and CEGUI::PropertySet::getProperty().
template<typename T> virtual void CEGUI::TypedProperty< T >::set (PropertyReceiver * receiver, const String & value) inline virtual
Sets the value of the property.
Parameters
receiver Pointer to the target object.
value A String object that contains a textual representation of the new value to assign to the Property.
Returns
Nothing.
Exceptions
InvalidRequestException Thrown when the Property was unable to interpret the content of value.
Implements CEGUI::Property.
template<typename T> virtual void CEGUI::TypedProperty< T >::setNative (PropertyReceiver * receiver, typename Helper::pass_type value) inline virtual
native set method, sets the property given a native type
See Also
Property::set
Referenced by CEGUI::TypedProperty< String >::set(), and CEGUI::PropertySet::setProperty().