Crazy Eddie's GUI System: CEGUI::Property Class Reference
CEGUI::Property Class Reference abstract
An abstract class that defines the interface to access object properties by name.
Inherits CEGUI::AllocatedObject< Property >.
Inherited by CEGUI::TypedProperty< T >, CEGUI::XercesParserProperties::SchemaDefaultResourceGroup, and CEGUI::TypedProperty< String >.
Public Member Functions
Property (const String &name, const String &help, const String &defaultValue="", bool writesXML=true, const String &dataType="Unknown", const String &origin="Unknown")
Creates a new Property object.
virtual ~Property (void)
Destructor for Property objects.
const String & getHelp (void) const
Return a String that describes the purpose and usage of this Property.
const String & getName (void) const
Return a the name of this Property.
const String & getDataType (void) const
Return string data type of this Property.
const String & getOrigin (void) const
Return string origin of this Property.
virtual String get (const PropertyReceiver *receiver) const =0
Return the current value of the Property as a String.
virtual void set (PropertyReceiver *receiver, const String &value)=0
Sets the value of the property.
virtual bool isDefault (const PropertyReceiver *receiver) const
Returns whether the property is at it's default value.
virtual String getDefault (const PropertyReceiver *receiver) const
Returns the default value of the Property as a String.
virtual void writeXMLToStream (const PropertyReceiver *receiver, XMLSerializer &xml_stream) const
Writes out an XML representation of this class to the given stream.
virtual bool isReadable () const
Returns whether the property is readable.
virtual bool isWritable () const
Returns whether the property is writable.
virtual bool doesWriteXML () const
Returns whether the property writes to XML streams.
virtual void initialisePropertyReceiver (PropertyReceiver *) const
function to allow initialisation of a PropertyReceiver.
virtual Property * clone () const =0
Static Public Attributes
static const String XMLElementName
static const String NameXMLAttributeName
static const String ValueXMLAttributeName
Protected Attributes
String d_name
String that stores the Property name.
String d_help
String that stores the Property help text.
String d_default
String that stores the Property default value string.
bool d_writeXML
Specifies whether writeXMLToStream should do anything for this property.
String d_dataType
Holds data type of this property.
String d_origin
Holds origin of this property.
Detailed Description
An abstract class that defines the interface to access object properties by name.
Property objects allow (via a PropertySet) access to certain properties of objects by using simple get/set functions and the name of the property to be accessed.
Constructor & Destructor Documentation
CEGUI::Property::Property (const String & name, const String & help, const String & defaultValue = "", bool writesXML = true, const String & dataType = "Unknown", const String & origin = "Unknown") inline
Creates a new Property object.
Parameters
name String containing the name of the new Property.
help String containing a description of the Property and it's usage.
defaultValue String holding the textual representation of the default value for this Property
writesXML Specifies whether the writeXMLToStream method should do anything for this Property. This enables selectivity in what properties within a PropertySet will get output as XML.
dataType String representation of the data type this property is held in ("int", "UVector2", ...)
origin String describing the origin class of this Property (Window, FrameWindow, ...)
Member Function Documentation
virtual String CEGUI::Property::get (const PropertyReceiver * receiver) const pure virtual
Return the current value of the Property as a String.
Parameters
receiver Pointer to the target object.
Returns
String object containing a textual representation of the current value of the Property
Implemented in CEGUI::TypedProperty< T >, CEGUI::TypedProperty< String >, and CEGUI::XercesParserProperties::SchemaDefaultResourceGroup.
Referenced by CEGUI::PropertySet::getProperty().
const String& CEGUI::Property::getDataType (void) const inline
Return string data type of this Property.
Returns
String containing the data type of the Property
virtual String CEGUI::Property::getDefault (const PropertyReceiver * receiver) const virtual
Returns the default value of the Property as a String.
Parameters
receiver Pointer to the target object.
Returns
String object containing a textual representation of the default value for this property.
const String& CEGUI::Property::getHelp (void) const inline
Return a String that describes the purpose and usage of this Property.
Returns
String that contains the help text
const String& CEGUI::Property::getName (void) const inline
Return a the name of this Property.
Returns
String containing the name of the Property
const String& CEGUI::Property::getOrigin (void) const inline
Return string origin of this Property.
Returns
String containing the origin of the Property
virtual bool CEGUI::Property::isDefault (const PropertyReceiver * receiver) const virtual
Returns whether the property is at it's default value.
Parameters
receiver Pointer to the target object.
Returns
true if the property has it's default value.
false if the property has been modified from it's default value.
virtual bool CEGUI::Property::isReadable () const virtual
Returns whether the property is readable.
Returns
true if the property is readable.
false if the property isn't readable.
Reimplemented in CEGUI::TplProperty< C, T >, and CEGUI::TplProperty< Window, String >.
Referenced by CEGUI::TypedProperty< String >::getNative().
virtual bool CEGUI::Property::isWritable () const virtual
Returns whether the property is writable.
Returns
true if the property is writable.
false if the property isn't writable.
Reimplemented in CEGUI::TplProperty< C, T >, and CEGUI::TplProperty< Window, String >.
Referenced by CEGUI::TypedProperty< String >::setNative().
virtual void CEGUI::Property::set (PropertyReceiver * receiver, const String & value) pure virtual
Sets the value of the property.
Parameters
receiver Pointer to the target object.
value A String object that contains a textual representation of the new value to assign to the Property.
Returns
Nothing.
Exceptions
InvalidRequestException Thrown when the Property was unable to interpret the content of value.
Implemented in CEGUI::TypedProperty< T >, CEGUI::TypedProperty< String >, and CEGUI::XercesParserProperties::SchemaDefaultResourceGroup.
Referenced by CEGUI::PropertySet::setProperty().
virtual void CEGUI::Property::writeXMLToStream (const PropertyReceiver * receiver, XMLSerializer & xml_stream) const virtual
Writes out an XML representation of this class to the given stream.
Note
This would normally have been implemented via XMLGenerator base class, but in this case we require the target PropertyReceiver in order to obtain the property value.
Reimplemented in CEGUI::Window::LookNFeelProperty, and CEGUI::Window::WindowRendererProperty.